<?php
/*
 * Copyright (c) 2014, webvariants GmbH & Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

print sly_Helper_Message::renderFlashMessage();

$system = new sly_Table('environment_system');
$system->setCaption(t('system'));
$system->addColumn(sly_Table_Column::factory(t('environment_system_component'), 'sly-col-title', '', array('width' => 250)));
$system->addColumn(sly_Table_Column::factory(t('environment_system_version'), 'sly-col-value'));
$system->openBuffer();

?>
	<tr>
		<th><?php print t('environment_version_system') ?></th>
		<td><?php print sly_Core::getVersion('R') ?></td>
	</tr>
	<tr>
		<th><?php print t('environment_version_php') ?></th>
		<td>
			<span class="pull-left"><?php print PHP_VERSION ?></span>
			<b class="caret pull-right" data-toggle="collapse" data-target="#system-php"></b>
		</td>
	</tr>
	<tr id="system-php" class="collapse">
		<td colspan="2">
			<dl>
				<dt>Operating System</dt>
				<dd><?php print php_uname('s') ?></dd>
				<dt>Release</dt>
				<dd><?php print php_uname('r') ?></dd>
				<dt>Version</dt>
				<dd><?php print php_uname('v') ?></dd>
				<dt>Machine</dt>
				<dd><?php print php_uname('m') ?></dd>
			</dl>
		</td>
	</tr>
	<tr>
		<th><?php print t('environment_version_database') ?></th>
		<td>
			<span class="pull-left"><?php print $database['version'] ?></span>
			<b class="caret pull-right" data-toggle="collapse" data-target="#system-database"></b>
		</td>
	</tr>
	<tr id="system-database" class="collapse">
		<td colspan="2">
			<dl>
				<dt>Driver</dt>
				<dd><?php print $database['driver'] ?></dd>
				<?php if (strtolower($database['driver']) === 'sqlite'): ?>
				<dt>Name</dt>
				<dd><?php print $database['name'] ?></dd>
				<?php else: ?>
				<dt>Host</dt>
				<dd><?php print $database['host'] ?></dd>
				<dt>Name</dt>
				<dd><?php print $database['name'] ?></dd>
				<dt>Login</dt>
				<dd><?php print $database['login'] ?></dd>
				<?php endif ?>
			</dl>
		</td>
	</tr>
<?

$system->closeBuffer();

print $system->render();
