<?php
/*
 * Copyright (c) 2014, webvariants GmbH & Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

print sly_Helper_Message::renderFlashMessage();

// build form

$form = new sly_Form($_router->getPlainUrl(null, 'update'), 'POST', '', '', 'sly-form-system');
$form->setSubmitButton(new sly_Form_Input_Button('submit', 'sendit', t('update')));
$form->setApplyButton();
$form->setResetButton();

// build form elements

$container = sly_Core::getContainer();

foreach ($types as $key => $name) {
	$types[$key] = sly_translate($name);
}

foreach ($languages as $id => $language) {
	$languages[$id] = $language->getName();
}

$availAdapters = $container['sly-cache-factory']->getAvailableAdapters();

foreach ($availAdapters as $name => $className) {
	$availAdapters[$name] = basename(str_replace('\\', '/', $className));
}

$timezoneSelect  = sly_Backend_Form_Helper::getTimezoneSelect();
$projectName     = new sly_Form_Input_Text('projectname', t('project_name'), sly_Core::getProjectName());
$startArticle    = new sly_Form_Widget_Link('start_article', t('start_article'), sly_Core::getSiteStartArticleId());
$notFound        = new sly_Form_Widget_Link('notfound_article', t('not_found_article'), sly_Core::getNotFoundArticleId());
$backendLocale   = new sly_Form_Select_DropDown('backend_locale', t('backend_locale'), sly_Core::getDefaultLocale(), $locales);
$defaultType     = new sly_Form_Select_DropDown('default_type', t('default_articletype'), sly_Core::getDefaultArticleType(), $types);
$cachingStrategy = new sly_Form_Select_DropDown('caching_strategy', t('caching_strategy'), sly_Core::getCachingStrategy(), $availAdapters);
$developerMode   = new sly_Form_Input_Checkbox('developer_mode', t('developer_mode'), '1', t('enabled'));

if (count($languages) === 1) {
	$form->addHiddenValue('default_clang', key($languages));
	$defaultClang = new sly_Form_Text(t('default_language'), reset($languages));
}
else {
	$defaultClang = new sly_Form_Select_DropDown('default_clang', t('default_language'), sly_Core::getDefaultClangId(), $languages);
}

// configure elements

$projectName->setRequired();
$startArticle->setRequired();
$notFound->setRequired();
$developerMode->setChecked(sly_Core::isDeveloperMode());

// assemble form

$form->beginFieldset(t('settings'), 'sly-system', 2);

$form->addRow(array($projectName));
$form->addRow(array($startArticle, $notFound));
$form->addRow(array($defaultClang, $defaultType));
$form->addRow(array($timezoneSelect, $backendLocale));
$form->addRow(array($cachingStrategy));
$form->addRow(array($developerMode));

print $form->render();
