<?php if (!$localmsg): ?>
<div id="messages"><?php print sly_Helper_Message::renderFlashMessage() ?></div>
<?php endif ?>

<div class="sly-content-header" data-slyid="<?php print $article->getId() ?>" data-slyclang="<?php print $article->getClang() ?>" data-slyrevision="<?php print $article->getRevision() ?>">
	<?php
	// navigation
	// @edge only show slots menu on the content page below meta fieldset
	// $this->render('content/_slotmenu.phtml',    array('article' => $article, 'slot' => $slot), false);
	$this->render('content/_subpagemenu.phtml', array('article' => $article), false);
	?>
</div>
