<?php
/*
 * Copyright (c) 2014, webvariants GmbH & Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

//////////////////////////////////////////////////////////////////
// start the form

$form = new sly_Form($_router->getPlainUrl(null), 'GET', '');
$form->setCsrfEnabled(false);
$form->setSubmitButton(null);
$form->setResetButton(null);
$form->beginFieldset(t('user'), '', 2);

//////////////////////////////////////////////////////////////////
// first row: login and last login

$try   = $user->getLastTryDate();
$login = new sly_Form_Text(t('username'), $user->getLogin());
$last  = new sly_Form_Text(t('last_login'), $try === 0 ? t('never') : sly_Util_String::formatDatetime($try));

$form->addRow(array($login, $last));

//////////////////////////////////////////////////////////////////
// second row: name and description

$name        = new sly_Form_Text(t('name'), $user->getName());
$description = new sly_Form_Text(t('description'), $user->getDescription());

$form->addRow(array($name, $description));

//////////////////////////////////////////////////////////////////
// third row: created and updated

if ($user) {
	$created = new sly_Form_Text(t('created_at'), sly_Util_HTML::getDatetimeTag($user->getCreateDate()), null, true);
	$updated = new sly_Form_Text(t('updated_at'), sly_Util_HTML::getDatetimeTag($user->getUpdateDate()), null, true);

	$form->addRow(array($created, $updated));
}

//////////////////////////////////////////////////////////////////
// fourth row: admin and status

$userAdmin  = new sly_Form_Input_Checkbox('is_admin', '', '1', t('admin'));
$userStatus = new sly_Form_Input_Checkbox('userstatus', '', '1', t('activated'));

$userAdmin->setChecked($user->isAdmin());
$userStatus->setChecked($user->getStatus());
$userAdmin->setDisabled(true);
$userStatus->setDisabled(true);

$form->addRow(array($userAdmin, $userStatus));

//////////////////////////////////////////////////////////////////
// fifth row: backend startpage and backend locale

$startPage     = $user->getStartPage();
$backendLocale = $user->getBackendLocale();
$startpages    = $this->getPossibleStartpages();
$locales       = $this->getBackendLocales();

if (!$startPage || !isset($startpages[$startPage])) {
	$startPage = t('profile');
}
else {
	$startPage = $startpages[$startPage];
}

$startpageSelect = new sly_Form_Text(t('startpage'), $startPage);
$localeSelect    = new sly_Form_Text(t('backend_locale'), $locales[$backendLocale]);

$form->addRow(array($startpageSelect, $localeSelect));

//////////////////////////////////////////////////////////////////
// let listeners extend the form

$eventparams = array('user' => $user);
$form = sly_Core::dispatcher()->filter('SLY_USER_VIEW_FORM', $form, $eventparams);

//////////////////////////////////////////////////////////////////
// Finally, render it!

print $form->render();
