<?php
/*
 * Copyright (c) 2013, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$viewURL    = $_router->getPlainUrl('content', null, array('article_id' => $article->getId(), 'clang' => $article->getClang()));
$editParams = array('category_id' => $article->getCategoryId(), 'clang' => $article->getClang(), 'edit_id' => $article->getId());

?>
<tr data-slyid="<?php echo $article->getId() ?>">
	<td class="sly-col-icon sly-icon"><?php echo sly_Util_Html::getSpriteLink($viewURL, '', 'article') ?></td>
	<td class="sly-col-name">
	<?php
		foreach($article->getParentTree() as $parent) {
			if ($parent) {
				print sly_html($parent->getName(). ' : ');
			}
		}
		print $article->getName();
	?>
	</td>
	<td class="sly-col-function">
		<?php
			$form = new sly_Form($_router->getUrl('trash', 'restore'), 'post', '');
			$form->addHiddenValue('id', $article->getId());
			$form->setSubmitButton(new sly_Form_Input_Button('submit', 'restore', t('restore_article')));
			$form->setResetButton();
			print $form->render();
		?>
	</td>
</tr>
