<?php
/*
 * Copyright (c) 2013, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

$callback = preg_replace('#[^a-z0-9.]#i', '', $callback);

?>
<script type="text/javascript">
var filename = <?php print json_encode($file) ?>;
var title    = <?php print json_encode($title) ?>;
var link     = 'mediapool/' + filename;
var callback = '<?php print $callback ?>' in window.opener ? window.opener['<?php print $callback ?>'] : null;
var fullName = '';

if (title.length === 0) {
	fullName = filename;
}
else {
	fullName = title;
}

// execute callback (media widget, WYMeditor, ...)
if (callback !== null) {
	callback(filename, fullName, title, link, window);
}

window.close();
</script>
