<?php
/*
 * Copyright (c) 2013, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

?>
	</div>
	<div id="sly-footer">
		<ul>
			<li class="sly-first"><a href="#sly-navi-top">&#94;</a></li>
			<li><a href="http://www.webvariants.de/" class="sly-blank">webvariants.de</a></li>
			<li><a href="http://www.sallycms.de/" class="sly-blank">sallycms.de</a></li>
			<?php if ($showCredits): ?>
			<li><a href="<?php print $_router->getUrl('credits') ?>"><?php echo t('credits') ?></a></li>
			<?php endif ?>
		</ul>
		<p>
			<?php if ($user && $runtime): ?>
			<span title="<?php echo sly_html($memory) ?>"><?php print sly_Util_String::formatTimespan($runtime) ?></span> |
			<?php endif ?>
			<?php print sly_Util_String::formatDatetime() ?>
		</p>
	</div>
</div>
