<?php
/*
 * Copyright (c) 2014, webvariants GmbH & Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

print '<nav class="sly-navigation">';

$groups = $nav->getGroups();

foreach ($groups as $group) {
	$topic    = $group->getName();
	$headline = $group->getTitle();
	$pages    = $group->getPages();
	$count    = 0;

	foreach ($pages as $page) {
		if ($page->isHidden()) continue;
		++$count;
	}

	if ($count == 0) continue;

	print '<ul id="sly-navi-'.$topic.'">';

	$first   = true;

	// Sort the addon group automatically, since we can't load the addOns in
	// a translated sorted way.

	if ($topic === 'addon') {
		$group->sortPages();
		$pages = $group->getPages();
	}

	foreach ($pages as $page) {
		if ($page->isHidden()) continue;

		$liclass  = 'sly-navigation-level-1';
		$liclass .= $page->isActive() ? ' sly-active' : ($page->getSubpages() ? ' collapsed' : '');
		$liclass .= $page->isPopup()  ? ' popup'      : '';
		$li       = array(
			'class' => $liclass,
			'id'    => 'sly-navi-page-'.$page->getPageParam()
		);

		$a = array('href' => $_router->getPlainUrl($page->getPageParam()));

		if ($first) {
			$li['class'] .= ' sly-first';
		}

		$a['class'] = $li['class'];

		$p        = $page->getName();
		$subpages = $page->getSubpages();
		$liAttr   = sly_Util_HTML::buildAttributeString($li);
		$aAttr    = sly_Util_HTML::buildAttributeString($a);


		// @edge / TODO
		//
		// fix subpages to work on mobile devices

		if (!empty($subpages)) {
			print '<li '.$liAttr.'><a '.$aAttr.' data-toggle="collapse" data-target="#sly-navi-page-'.$page->getPageParam().'-collapse" onclick="return false;"><span class="sly-page-title">'.$page->getTitle().'</span></a>';
		}
		else {
			print '<li '.$liAttr.'><a '.$aAttr.'><span class="sly-page-title">'.$page->getTitle().'</span></a>';
		}

		// ***** Subnavi
		if (!empty($subpages)) {
			print '<ul id="sly-navi-page-'.$page->getPageParam().'-collapse" class="collapse'.($page->isActive() ? ' in' : '').'">';
			$first = true;

			foreach ($subpages as $sp) {
				$param = $sp->getPageParam();
				$class = 'sly-navigation-level-2';
				$id    = 'sly-navi-'.$p.'-subpage-'.$param;
				$href  = $_router->getPlainUrl($param, '', $sp->getExtraParams());

				if ($first)          $class .= ' sly-first';
				if ($sp->isActive()) $class .= ' sly-active';

				$liAttr = sly_Util_HTML::buildAttributeString(array('class' => $class, 'id' => $id));
				$aAttr  = sly_Util_HTML::buildAttributeString(array('class' => $class, 'href' => $href));

				print '<li '.$liAttr.'><a '.$aAttr.'>'.$sp->getTitle().'</a></li>';
				$first = false;
			}

			print '</ul>';
		}

		print '</li>';

		$first = false;
	}

	print '</ul>';
}

print '</nav>';
